import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowLeft, CheckCircle2, CreditCard, MapPin, Smartphone } from "lucide-react";
import { useCart } from "../context/CartContext";

export default function Checkout() {
  const { cart, subtotal, delivery, total, clearCart } = useCart();
  const nav=useNavigate();
  const [placed,setPlaced]=useState(false);
  const [form,setForm]=useState({name:"",phone:"",address:"",city:"Mumbai",payment:"cod"});
  const [orderId]=useState("FD"+Math.floor(100000+Math.random()*900000));
  const submit=e=>{e.preventDefault();setPlaced(true);clearCart();};
  if(placed) return <main className="page"><div className="container"><div className="success-box"><span className="success-icon"><CheckCircle2/></span><span className="eyebrow">ORDER CONFIRMED</span><h1>You're all set!</h1><p>Your order <b>#{orderId}</b> has been placed. Your food is being prepared with love.</p><div className="tracking"><span className="done">✓</span><div><b>Expected delivery</b><small>25–35 minutes • We'll keep you updated</small></div></div><Link to="/orders" className="primary-btn">Track order</Link></div></div></main>;
  if(!cart.length) return <main className="page"><div className="empty-state"><span>🛒</span><h2>Your cart is empty</h2><Link to="/menu" className="primary-btn">Go to menu</Link></div></main>;
  return <main className="page"><div className="container"><Link to="/cart" className="back-link"><ArrowLeft/> Back to cart</Link><div className="checkout-grid"><form className="checkout-form" onSubmit={submit}><div className="page-heading compact"><span className="eyebrow">CHECKOUT</span><h1>Almost <em>there.</em></h1></div><section className="form-section"><h3><MapPin/> Delivery details</h3><div className="form-grid"><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><label>Phone number<input required pattern="[0-9]{10}" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="10-digit mobile number"/></label></div><label>Address<textarea required value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="House no., street, landmark"></textarea></label><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label></section><section className="form-section"><h3><CreditCard/> Payment method</h3><div className="payment-options"><label className={form.payment==="cod"?"checked":""}><input type="radio" name="payment" value="cod" checked={form.payment==="cod"} onChange={e=>setForm({...form,payment:e.target.value})}/><span>💵</span><div><b>Cash on Delivery</b><small>Pay when your food arrives</small></div></label><label className={form.payment==="upi"?"checked":""}><input type="radio" name="payment" value="upi" checked={form.payment==="upi"} onChange={e=>setForm({...form,payment:e.target.value})}/><span>📱</span><div><b>UPI / Wallet</b><small>Demo payment interface</small></div></label><label className={form.payment==="card"?"checked":""}><input type="radio" name="payment" value="card" checked={form.payment==="card"} onChange={e=>setForm({...form,payment:e.target.value})}/><span>💳</span><div><b>Credit / Debit Card</b><small>Secure demo checkout</small></div></label></div></section><button className="primary-btn place-order" type="submit">Place order • ₹{total}</button></form><aside className="summary checkout-summary"><h2>Your order</h2>{cart.map(x=><div className="mini-item" key={x.id}><img src={x.image}/><span>{x.name}<small>Qty {x.quantity}</small></span><b>₹{x.price*x.quantity}</b></div>)}<div className="sum-lines"><span>Subtotal <b>₹{subtotal}</b></span><span>Delivery <b>{delivery===0?"FREE":`₹${delivery}`}</b></span></div><div className="sum-total"><span>Total</span><strong>₹{total}</strong></div></aside></div></div></main>;
}